### PR TITLE
Implemented all the UTC TODOs

### PR DESCRIPTION
**Pull request by kevin-wise-infusionsoft**
Implemented all the UTC TODOs

### CODE REVIEW

**Comment by bbooth** [comment]
Without fixing existing dates in the database this will cause problems.

**Comment by kevin-wise-infusionsoft** [comment]
@bbooth it affects UserPassword and LoginAttempt. It's not going to make any difference if the password expires in 90 days or 90 days + 7 hours. And LoginAttempt is cleared every day, so it will fix itself.

**Comment by bbooth** [comment]
LoginAttempt is used to unlock users as well.  AC will write an non UTC date in there and unlocking might now work.

**Comment by kevin-wise-infusionsoft** [comment]
You're right. Changing to UTC would give temporarily older times. If someone tries to unlock immediately after, there would be a 4-5 hour window where unlocks wouldn't work unless the lockout was older than that, which they never are because they only last 30 minutes. And you'd also essentially have login attempts in the future. and we'd also have to update account central with similar logic. Closing for now.

**Pull request closed without merging**
